version: "3"
services:

  mongo:
    image: mongo
    ports:
        - "2811:27017"

  seed:
    image: karpikpl/really-cloudy_seed:latest
    links:
      - mongo

  web:
    image: karpikpl/really-cloudy_web:latest
    ports:
      - "80:3000"
    links:
      - mongo
      - seed
